### ISSUE TITLE
bootstrap fails on fresh Debian 10 install

### ISSUE THREAD

**Issue by dagerman** [hijiahanwang/s3-tests#7]
Trying to install (on a clean AWS Debian 10 instance) per readme leads to "BackendUnavailable" error.

```
./bootstrap: missing required DEB packages. Installing via sudo.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libxslt1-dev is already the newest version (1.1.32-2.2~deb10u1).
The following packages were automatically installed and are no longer required:
  libargon2-1 libcryptsetup12 systemd
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/admin/s3-tests/virtualenv/bin/python2
Not overwriting existing python script /home/admin/s3-tests/virtualenv/bin/python (you must use /home/admin/s3-tests/virtualenv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: pip in ./virtualenv/lib/python2.7/site-packages (20.3.4)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting setuptools==32.3.1
  Using cached setuptools-32.3.1-py2.py3-none-any.whl (479 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
      Successfully uninstalled setuptools-44.1.1
Successfully installed setuptools-32.3.1
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting PyYAML
  Using cached PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574 kB)
Collecting nose>=1.0.0
  Using cached nose-1.3.7-py2-none-any.whl (154 kB)
Collecting boto>=2.6.0
  Using cached boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
Collecting bunch>=1.0.0
  Using cached bunch-1.0.1.tar.gz (6.6 kB)
Collecting gevent>=1.0
  Using cached gevent-21.8.0.tar.gz (6.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
**ERROR: Exception:
Traceback (most recent call last):
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 180, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 385, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 337, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 39, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_internal/distributions/sdist.py", line 97, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 178, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/admin/s3-tests/virtualenv/local/lib/python2.7/site-packages/pip/_vendor/pep517/wrappers.py", line 284, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
BackendUnavailable**
```

**Comment by kaloyan-raev** [comment]
I've just got the same error when trying to bootstrap in a fresh Ubuntu 18.04 VM.

**Comment by kaloyan-raev** [comment]
Found a workaround: modify the bootstrap script to not use `virtualenv`. Now, it finishes successfully for me.
